---
- hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
    - DB_USERNAME: "{{ lookup('env','DB_USERNAME') }}"
    - DB_PASSWORD: "{{ lookup('env','DB_PASSWORD') }}"
    - DB_NAME: "{{ lookup('env','DB_NAME') }}"
  tasks:
    - name: Install bash, OpenSSl, and libssl latest versions
      apt: name={{ item }} update_cache=true state=latest
      with_items:
        - bash
        - openssl
        - libssl-dev
        - libssl-doc
      tags: packages

    - name: Install PostgreSQL
      apt: name={{ item }} update_cache=true state=installed
      with_items:
        - postgresql
        - postgresql-contrib
        - libpq-dev
        - python3-psycopg2
      tags: packages

    - name: Start the postgreSQL service
      service: name=postgresql state=started enabled=yes

    - name: Create the database
      sudo_user: postgres
      postgresql_db: name={{ DB_NAME }}
                encoding='UTF-8'
                lc_collate='en_US.UTF-8'
                lc_ctype='en_US.UTF-8'
                template='template0'
                state=present

    - name: Grant priviledges to the user
      sudo_user: postgres
      postgresql_user: db={{ DB_USERNAME }}
                  name={{ DB_USERNAME }}
                  password={{ DB_PASSWORD }}
                  priv=ALL
                  state=present

    - name: Limit user privileges
      sudo_user: postgres
      postgresql_user: name={{ DB_USERNAME }}
                  role_attr_flags=NOSUPERUSER,NOCREATEDB
                  state=present
